server:
  port: 8080
#  ssl:
#    certificate: "classpath:ssl.pem"
#    certificate-private-key: "classpath:ssl.key"
#    trust-certificate: "classpath:ssl.pem"
spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3306/oz_order
    username: root
    password: renzhe2zhuzhu
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  config: classpath:log4j2.xml


table:
  name: order